<?php
return[
    "habis",
    "tekanan",
    "terima",
    "kecelakaan",
    "prestasi",
    "acara",
    "acaranya",
    "acaranya",
    "aksi",
    "aktif",
    "aktivitas",
    "sebenarnya",
    "sebenarnya",
    "ada",
    "ada",
    "dewasa",
    "petualangan",
    "petualang",
    "nasehat",
    "setelah",
    "sore",
    "lagi",
    "perwakilan",
    "agen",
    "agak",
    "angkatan",
    "setuju",
    "persetujuan",
    "saya",
    "saja",
    "saja",
    "saja",
    "saja",
    "saja",
    "ajak",
    "saya",
    "banyak",
    "akhirnya",
    "aktifkan",
    "saya",
    "alhamdulillah",
    "alhamdulillah",
    "hampir",
    "alamat",
    "sendiri",
    "alasan",
    "juga",
    "selalu",
    "sama",
    "mengagumkan",
    "sampai",
    "kamu",
    "kamu",
    "memang",
    "hancur",
    "saya",
    "hangat",
    "apple",
    "aplikasi",
    "diterima",
    "saya",
    "saya",
    "saya",
    "saya",
    "mau",
    "tiba",
    "artikel",
    "artinya",
    "tugas",
    "bantuan",
    "asisten",
    "asyik",
    "atas",
    "satu-satu",
    "atau",
    "otomatis",
    "ada",
    "bb",
    "berkesinambungan",
    "ayah",
    "balasannya",
    "balas",
    "bangga",
    "baterai",
    "beberapa",
    "beberapa",
    "beberapa",
    "bandung",
    "pantai",
    "sebelum",
    "banget",
    "bodoh",
    "belikan",
    "malam",
    "memar",
    "beraktivitas",
    "berjalan",
    "berkemampuan",
    "bersamaan",
    "banget",
    "better",
    "antara",
    "bagaimana",
    "bagaimana",
    "bagaimana",
    "bangun",
    "banget",
    "begitu",
    "bahasa",
    "bimbingan belajar",
    "ulang tahun",
    "habis",
    "berjalan",
    "bakalan",
    "bukan",
    "blackberry",
    "bilang",
    "balik",
    "belum",
    "bulan",
    "bilang",
    "belanja",
    "belum",
    "belum",
    "balas",
    "balasannya",
    "belum",
    "bbm",
    "benar",
    "benar",
    "benar",
    "beneran",
    "sebentar",
    "bantu",
    "bunuh",
    "banyak",
    "tidurnya",
    "bodoh",
    "ayah",
    "boleh",
    "bohong",
    "bosan",
    "bapak",
    "bapak",
    "berangkat",
    "berangkat",
    "berenang",
    "barang",
    "berapa",
    "berapa",
    "bersih",
    "baru",
    "bisa",
    "bisa",
    "besar",
    "basah",
    "besok",
    "besok",
    "besar",
    "butuh",
    "butuh",
    "betul",
    "ngomong ngomong",
    "banget",
    "banget",
    "banget",
    "buktikan",
    "buktikan",
    "bulan",
    "bungkus",
    "bawa",
    "bawa",
    "bawah",
    "untuk",
    "bawah",
    "untuk",
    "bayar",
    "banyak",
    "bayar",
    "cabai",
    "cerdas",
    "bocah",
    "telepon",
    "dapat",
    "capek",
    "mobil",
    "karir",
    "perhatian",
    "coba",
    "teman",
    "semangat",
    "semangat",
    "cepat",
    "cewek",
    "cewek",
    "cek",
    "siapa",
    "sibuk",
    "cinta",
    "serius",
    "seriusan",
    "serius",
    "celananya",
    "campakkan",
    "campakkan",
    "canda",
    "canda",
    "canggih",
    "canggih",
    "cinta",
    "cinta",
    "cantik",
    "cantik",
    "tengah",
    "cowok",
    "pelatih",
    "alas",
    "cocokkan",
    "cocoknya",
    "kelapa",
    "bayar saat pengiriman",
    "mengkode",
    "cokelat",
    "mengoleksi",
    "koleksi",
    "curikan",
    "kolonial",
    "warna",
    "berwarna-warni",
    "warna",
    "datang kembali",
    "komedi",
    "patut dihargai",
    "komen",
    "komersil",
    "datang",
    "konfirmasi",
    "nyaman",
    "menyenangkan",
    "komik",
    "datang",
    "segera datang",
    "segera datang",
    "prajurit",
    "patut dihargai",
    "komen",
    "uraian",
    "komersil",
    "komunita",
    "komunitanya",
    "perusahaan",
    "persaingan",
    "mengeluh",
    "lengkap",
    "lengkap",
    "pujian",
    "menyusun",
    "menghitung",
    "komunita",
    "komunitanya",
    "konsep",
    "konser",
    "kondisi",
    "mengkondisikan",
    "menghubungkan",
    "koneksi",
    "yakin",
    "susunan",
    "konfirmasi",
    "bingung",
    "bingung",
    "bingung",
    "selamat",
    "selamat",
    "selamat",
    "selamat",
    "konsep",
    "mempertimbangkan",
    "berunding",
    "konsultan",
    "konsumen",
    "kontak",
    "kontak",
    "isi",
    "kontes",
    "contohnya",
    "kontra",
    "kontrak",
    "kontrol",
    "konvensi",
    "konvoi",
    "memasak",
    "copy paste",
    "lepas",
    "sudut",
    "sudut",
    "corolla",
    "koreksi",
    "koridor",
    "kosmetik",
    "ongkos",
    "ongkos",
    "kostum",
    "dapat",
    "dewan",
    "perhitungan detik-detik terakhir",
    "alat perhitungan",
    "negara",
    "daerah pedalaman",
    "pasangan",
    "sepupu",
    "cowok",
    "cowok",
    "cepat",
    "cara",
    "gila",
    "cari",
    "cerita",
    "ceritanya",
    "cocok",
    "cukup",
    "cuma",
    "hanya",
    "curhat",
    "cewek",
    "cowok",
    "cowok",
    "serius",
    "sudah",
    "jalan",
    "bahaya",
    "dahsyat",
    "tanggal",
    "datang",
    "datanglah",
    "hari",
    "dibalas",
    "dibantu",
    "didalam",
    "duduk",
    "pertahanan",
    "membela",
    "deg-degan",
    "deg-degan",
    "deg-degan",
    "deg-degan",
    "deg-degan",
    "dekat",
    "desak-desakan",
    "desakan",
    "sendiri",
    "daftar",
    "dengan",
    "dengan",
    "dengar",
    "dengarkan",
    "dengarkan",
    "sudah",
    "dibanggakan",
    "dibalas",
    "diganggu",
    "diberi izin",
    "dikasih",
    "dikasihnya",
    "sedikit",
    "di kelas",
    "dilihat",
    "sebentar",
    "dimana-mana",
    "dimakan",
    "dimaksud",
    "dimana-mana",
    "dimana",
    "diinstall",
    "dipakai",
    "dipanggilnya",
    "dipakai",
    "dilempar",
    "disebelah",
    "diskon",
    "diskon",
    "diskon",
    "diseberang",
    "disebuah",
    "di sekolah",
    "di sekolahan",
    "disekolahkan",
    "diselenggarakan",
    "diselimuti",
    "di senayan",
    "di senen",
    "di sentul",
    "diservis",
    "dinas perhubungan",
    "dinas perhubungan komunikasi dan informatika",
    "diisi",
    "disia-siakan",
    "disimpan",
    "disimpang",
    "disini",
    "di sekolah",
    "diskonnya",
    "diskonnya",
    "diskonnya",
    "diskonnya",
    "disini",
    "disana",
    "disana",
    "distribusi",
    "daerah",
    "hancur",
    "ganggu",
    "di surga",
    "disuruh",
    "disuruh",
    "ditabrak",
    "ditraktir",
    "di taman",
    "ditambahkan",
    "di tanah",
    "ditanggapin",
    "ditanggapin",
    "ditangkap",
    "ditangkapinnya",
    "ditangkapinnya",
    "ditanggung",
    "ditaruh",
    "ditaruh",
    "ditelan",
    "ditemani",
    "ditemani",
    "ditraktir",
    "ditinggal",
    "ditinggali",
    "ditinggikan",
    "ditukarkan",
    "ditelepon",
    "di tempat",
    "ditengah",
    "ditungguin",
    "ditunggu",
    "ditunjukkan",
    "di toko",
    "ditraktir",
    "di trotoar",
    "di tugu",
    "ditukar",
    "dibelikan",
    "dibelikan",
    "dibelikan",
    "dinaiki",
    "di tunas",
    "ditunggu-tunggu",
    "ditunggu",
    "ditunggu-tunggu",
    "ditunggu",
    "ditunjukkan",
    "ditunjukkan",
    "diturunkan",
    "di warnet",
    "di akhir pekan",
    "dibalik",
    "dijaga",
    "dijemput",
    "di jakarta",
    "di jalan",
    "dikasih",
    "dekat",
    "dekatkan",
    "dekat",
    "dekat",
    "sedikit",
    "dan kawan-kawan",
    "di klinik",
    "dikeluarkan",
    "di kampus",
    "dikomplain",
    "dikasih",
    "dekat",
    "dukung",
    "dulu",
    "dilakukan",
    "dilakukan",
    "dalam",
    "dilanjutkan",
    "dilihat",
    "diliburkan",
    "dan lain-lain",
    "dalam",
    "dilanjutkan",
    "dulu",
    "duluan",
    "dimainkan",
    "dimakan",
    "demam",
    "demamnya",
    "dimana",
    "dimana",
    "diminta",
    "dimana",
    "dimana",
    "dimana-mana",
    "dimananya",
    "dimananya",
    "dimana",
    "diminta",
    "dimananya",
    "di mobil",
    "di monas",
    "di motor",
    "dan",
    "dengan",
    "dengan",
    "dengar",
    "dengar dengar",
    "dengarkan",
    "dipakai",
    "dingin",
    "dinginan",
    "dengan",
    "doakan",
    "doanya",
    "saja",
    "saja",
    "pada lupa",
    "bermain",
    "unduh",
    "unduh",
    "unduh",
    "jangan",
    "dapat",
    "dapatkan",
    "dapat",
    "depan",
    "dipastikan",
    "dapat",
    "dari",
    "dari",
    "daripada",
    "daripada",
    "di rumah",
    "darimana",
    "daripada",
    "daritadi",
    "disana",
    "dasar",
    "dan sebagainya",
    "disini",
    "disitu",
    "di sekolah",
    "di sekitar",
    "desember",
    "disana",
    "disini",
    "disana",
    "disuruh",
    "dan seterusnya",
    "datang",
    "datang",
    "datang",
    "datangin",
    "diturunkan",
    "duitnya",
    "selama",
    "punya",
    "duit",
    "dia",
    "kamu",
    "kamu",
    "emang",
    "emang",
    "tidak mau",
    "sendiri",
    "indonesia",
    "beneran",
    "tidak",
    "tidak",
    "tidak",
    "tidak",
    "enak",
    "cukup",
    "nanti",
    "ringan",
    "enak",
    "dan lain-lain",
    "acara",
    "setiap",
    "semua orang",
    "segala sesuatu",
    "dimanapun",
    "contoh",
    "bagus",
    "keluar",
    "muka",
    "fakta",
    "gagal",
    "ayah",
    "biaya",
    "ferrari",
    "film",
    "akhirnya",
    "fokus",
    "follow back",
    "follow back nya",
    "follow back",
    "follow back",
    "follow back",
    "follow back nya",
    "follow back",
    "follow back nya",
    "follow back",
    "follow",
    "follow back",
    "follow",
    "follow",
    "follow back",
    "follow back",
    "follow back",
    "sepak bola",
    "untuk",
    "lupa",
    "lupa",
    "lupa",
    "foto-foto",
    "jumat",
    "teman",
    "profil",
    "dari",
    "fungsi",
    "lucu",
    "fungsi",
    "lucu",
    "tidak",
    "tidak",
    "tidak ada",
    "tidak akan",
    "tidak asik",
    "tak akan",
    "tidak bareng",
    "tidak bebas",
    "tidak beda",
    "tidak berani",
    "tidak bilang",
    "tidak bisa",
    "tidak boleh",
    "tidak boleh",
    "tidak bosen",
    "tidak bisa",
    "tidak ada",
    "tidak ada",
    "gadaikan",
    "tidak dapat",
    "gadaikan",
    "tidak dekat",
    "tidak diajak",
    "tidak dibalas",
    "membuat",
    "pekerjaan",
    "tidak enak",
    "biasanya",
    "tidak",
    "gaul",
    "gaul",
    "tidak ikut",
    "tidak ikutan",
    "tidak ikutan",
    "tidak bisa",
    "tidak jadi",
    "tidak jalan",
    "tidak janji",
    "tidak jauh",
    "tidak jadi",
    "tidak jelas",
    "tidak jelas",
    "tidak menjenguk",
    "tidak",
    "tidak ada",
    "tidak akan",
    "tidak bilang",
    "tidak bisa",
    "tidak deh",
    "tidak enak",
    "tidak jadi",
    "tidak mau",
    "tidak apa-apa",
    "tidak penting",
    "tidak pernah",
    "tidak sabar",
    "tidak semua",
    "tidak sih",
    "tidak tau",
    "tidah tuh",
    "tidak main",
    "tidak malas",
    "tidak mau",
    "tidak masuk",
    "tidak mau",
    "tidak masuk",
    "tidak muat",
    "tidak mungkin",
    "juragan",
    "tidak mengajak",
    "tidak mengerti",
    "gangguin",
    "gantikan",
    "ganti saja",
    "tidak usah",
    "tidak pada",
    "tidak paham",
    "tidak pakai",
    "tidak apa-apa",
    "tidak percaya",
    "tidak perlu",
    "tidak pernah",
    "tidak apa-apa",
    "gagap teknologi",
    "tidak pulang",
    "gara-gara",
    "tidak sabar",
    "tidak salah",
    "tidak sanggup",
    "tidak secerah",
    "tidak sedingin",
    "tidak sekeras",
    "tidak seru",
    "tidak sia-sia",
    "tidak sih",
    "datang lebih awal",
    "tidak suka",
    "tidak tau",
    "gatal",
    "gatal",
    "tidak tuh",
    "tidak usah",
    "tidak usah",
    "tidak usah",
    "bawakan",
    "bawakan",
    "gayamu",
    "tidak bawa",
    "gelora bung karno",
    "tidak bilang",
    "tidak balik",
    "tidak bisa",
    "tidak bisa",
    "tidak ada",
    "pasangan",
    "pasangan",
    "bodoh",
    "besar",
    "besarnya",
    "besar-besaran",
    "bersedia",
    "gila",
    "bodoh",
    "bodoh",
    "gemuk",
    "begitu",
    "begitu",
    "tidak",
    "gila",
    "gila",
    "bagaimana",
    "bagaimana",
    "bagaimana",
    "begini",
    "begitu",
    "begituan",
    "begitu",
    "tidak jadi",
    "tidak jadi",
    "tidak jelas",
    "tidak janji",
    "tidak",
    "gambar",
    "bagaimana",
    "bagaimana",
    "bagaimana",
    "ganti",
    "lima ribu",
    "godaan",
    "semoga berhasil",
    "selamat pagi",
    "gara-gara",
    "tidak pakai lama",
    "tidak-apa-apa",
    "tidak apa-apalah",
    "gara-gara",
    "gara-gara",
    "tingkat",
    "begitu",
    "begitu",
    "tidak tau",
    "saya",
    "saya",
    "saya",
    "saya",
    "saya",
    "saya",
    "tidak",
    "sedang",
    "hanya",
    "hp",
    "senang",
    "senang",
    "selamat ulang tahun",
    "perempuan",
    "harga",
    "harganya",
    "harganya",
    "asyik",
    "lhawong",
    "selamat ulang tahun",
    "habis",
    "hadiah",
    "hadiahnya",
    "hadirkan",
    "hidup",
    "hadapan",
    "hidup",
    "error",
    "hidup",
    "hidupmu",
    "hingga",
    "hempas",
    "hampir",
    "hantu",
    "hanya",
    "hanya",
    "ngantuk",
    "jujur",
    "hari",
    "harapan",
    "harga",
    "harga",
    "harganya",
    "hari",
    "harus",
    "harusnya",
    "harus",
    "harus",
    "hasil",
    "hasil",
    "hotelnya",
    "hatiku",
    "hubungi",
    "lapar",
    "ibadah",
    "hidung",
    "izin",
    "hijau",
    "ini",
    "ikut",
    "ikutan",
    "ikutan",
    "ikut",
    "hilang",
    "gambar",
    "kotak masuk",
    "incaran",
    "termasuk",
    "indah",
    "indonesia",
    "informasi",
    "informasinya",
    "informasi",
    "informasikan",
    "informasinya",
    "ingat",
    "inginnya",
    "ingat",
    "ingatan",
    "inovasi",
    "informasi",
    "informasi",
    "insyaallah",
    "insyaallah",
    "insyaallah",
    "insyaallah",
    "insyaallah",
    "internet",
    "mengajak",
    "mengajak",
    "mengajak",
    "iya",
    "hitam",
    "masih",
    "masih",
    "malu",
    "isinya",
    "bisa",
    "istri",
    "istirahat",
    "pagi",
    "hitung",
    "iya",
    "iya dah",
    "iya dah",
    "iya dong",
    "iya dong",
    "iya",
    "iya nih",
    "iya sih",
    "iya",
    "iya",
    "iya dah",
    "iyalah",
    "iya",
    "iya",
    "iya",
    "iya sih",
    "iya",
    "iya",
    "saja",
    "saja",
    "jawa barat",
    "jadinya",
    "jadinya",
    "jaman dulu",
    "jadwalnya",
    "jahatnya",
    "jakarta pusat",
    "jakarta",
    "jakarta selatan",
    "jakarta timur",
    "jalan-jalan",
    "jalankan",
    "jalannya",
    "jamannya",
    "jamannya",
    "jamannya",
    "jamannya",
    "jamannya",
    "jangan",
    "jepang",
    "kata",
    "jaringannya",
    "jaringan",
    "jawa tengah",
    "jatuh",
    "jazz",
    "jadi",
    "jadi",
    "jadian",
    "namanya",
    "beri nama",
    "jeep",
    "juga",
    "juga",
    "jogja",
    "jangan",
    "jangan-jangan",
    "jangankan",
    "jahat",
    "jujur",
    "jika",
    "jakarta",
    "jakarta",
    "jakarta",
    "jalan",
    "jalan-jalan",
    "jelas",
    "jalan",
    "jalan-jalan",
    "jelas",
    "jembatan",
    "jembatan",
    "jamin",
    "jumlah",
    "jaman",
    "jumpa",
    "jumpa",
    "jemput",
    "jemputnya",
    "jangan",
    "pencari kerja",
    "jari",
    "jaringan",
    "jaringan",
    "jaringan",
    "jatuh",
    "juga",
    "juga",
    "juga",
    "juga",
    "juga",
    "jawab",
    "jawaban",
    "jawabannya",
    "jawabannya",
    "jawabannya",
    "kabarnya",
    "semua",
    "kasihan",
    "kesini",
    "kesitu",
    "tidak",
    "tidak",
    "tidak",
    "kebanyakan",
    "kali",
    "kalau",
    "kalau",
    "kapan",
    "kepala kepolisian resor",
    "terserah kamu",
    "karena",
    "sama",
    "ganteng",
    "kasih",
    "kasihan",
    "kata-kata",
    "kata-katanya",
    "katanya",
    "katanya",
    "seperti",
    "kebagusan",
    "kabar",
    "kabarnya",
    "kabari",
    "semua",
    "terbeli",
    "keberangkatan",
    "kebahagiaan",
    "kebahagiaan",
    "kabar",
    "kabari",
    "kabarnya",
    "kebetulan",
    "terbuka",
    "kebun",
    "kecepatan",
    "kecil",
    "kecintaan",
    "kecintaan",
    "kecelakaan",
    "kecelakaan",
    "kacamata",
    "kedepannya",
    "kedepannya",
    "terkadang",
    "kadang-kadang",
    "kesitu",
    "kedalam",
    "kedepan",
    "terbeli",
    "ke bengkel",
    "kebersamaannya",
    "kebersihan",
    "kebanyakan",
    "kerbau",
    "keberangkatan",
    "kebudayaan",
    "ke bulan",
    "ke bumi",
    "kebut-kebutan",
    "kebawah",
    "kecewa",
    "gaul",
    "capek",
    "kecelakaannya",
    "kecelakaan",
    "kecelakaannya",
    "pasangan",
    "kecapean",
    "terlalu cepat",
    "keceriaan",
    "kasihan",
    "ke cimanggis",
    "ke cimanggis",
    "ke cipondoh",
    "ke daerah",
    "kedatangannya",
    "kedatangan",
    "terlalu panjang",
    "terlalu dekat",
    "kedengaran",
    "kedepan",
    "kedepannya",
    "kedepannya",
    "kedatangan",
    "ke dufan",
    "keenakan",
    "terlalu besar",
    "terlalu besar",
    "kegembiraan",
    "kehadirannya",
    "ke hulu",
    "ke hutan",
    "keindahan",
    "keikhlasan",
    "kehilangan",
    "teringat",
    "keinginannya",
    "keistimewaan",
    "terhitung",
    "kejadian",
    "ke jakarta",
    "kejar-kejaran",
    "kejauhan",
    "kejayaan",
    "terjepit",
    "terjual",
    "kejuaraan",
    "seperti",
    "kekalemannya",
    "ke kamar",
    "ke kampus",
    "ke kandang",
    "ke kasur",
    "kekecewaan",
    "ke kemayoran",
    "bagaimana",
    "kayaknya",
    "ke kontrakan",
    "ke kos",
    "ke kosanku",
    "ke kota",
    "kekuasaan",
    "terkumpul",
    "terkunci",
    "kekurangannya",
    "terkuras",
    "terlaksana",
    "kelaparan",
    "ke laut",
    "kereta",
    "kelihatan",
    "kelihatannya",
    "kelihatannya",
    "kelihatannya",
    "terlindas",
    "terlindas",
    "kerja",
    "ke lokasi",
    "keluarkan",
    "kemana-mana",
    "kemarahannya",
    "kembarannya",
    "kembangkan",
    "kementerian pendidikan nasional",
    "kementerian kesehatan",
    "kementerian keuangan",
    "kementerian komunikasi dan informatika",
    "kementerian hukum dan hak asasi manusia",
    "kemana",
    "kementerian perumahan rakyat",
    "kementerian perindustrian",
    "kementerian",
    "kemerdekaan",
    "kamis",
    "ke monas",
    "kemarin",
    "kemuliaan",
    "kemuliaan",
    "ke museum",
    "kenalkan",
    "kenang-kenangan",
    "kenang-kenangan",
    "kenangannya",
    "kenapa",
    "kenapa ya",
    "kenapa",
    "cepat",
    "kendaraan",
    "kendaraannya",
    "kendaraan",
    "kena",
    "kenapa",
    "kenapa",
    "kenyataan",
    "kenyataannya",
    "terpakai",
    "kepalanya",
    "terpanggang",
    "terpanggang",
    "ke pantai",
    "ke pantainya",
    "ke paris",
    "ke pasar",
    "kepastiannya",
    "terpencar",
    "terpencet",
    "ingin",
    "keinginannya",
    "ingin",
    "kepercayaan",
    "kepercayaannya",
    "terpilih",
    "terpincut",
    "kepintaran",
    "keponakannya",
    "terpotong",
    "kepercayaan",
    "kepercayaan",
    "kepribadiannya",
    "kepala sekolah",
    "ke pulau",
    "ke puncak",
    "terputar",
    "keputusannya",
    "ke ragunan",
    "kerajaan",
    "keras-keras",
    "terasa",
    "kardus",
    "miskin",
    "kering-kering",
    "keringat",
    "kerja",
    "kerjakan",
    "pekerjaan",
    "ke rumah",
    "kesabarannya",
    "kesalahannya",
    "ke salon",
    "kesampaian",
    "ke samping",
    "kesannya",
    "tersangkut",
    "kesannya",
    "tersasar",
    "ke sawah",
    "kesayangannya",
    "kesederhanaan",
    "kesediaan",
    "kesediaannya",
    "ke sekolah",
    "terselip",
    "kesetiaan",
    "kesetiaanmu",
    "kesetiaannya",
    "kasihan",
    "ke sekolah",
    "kesampaian",
    "kesana",
    "kesini",
    "kesana",
    "ke saudara",
    "ke sekolah",
    "kesana",
    "kesukaan",
    "keterangan",
    "tertabrak",
    "tertagih",
    "tertarik",
    "tertawa",
    "ketawa-tawa",
    "ketentuannya",
    "keterpurukannya",
    "tertimpa",
    "ketidaknyamanannya",
    "ke tidung",
    "ketika",
    "tertimpa",
    "ketinggalan",
    "terlihat",
    "sepertinya",
    "keterangan",
    "keterangan",
    "ketuaan",
    "ketukar",
    "tertutup",
    "keunggulan",
    "keunggulannya",
    "kewarganegaraan",
    "ke warung internet",
    "kata kunci",
    "tidak",
    "tidak",
    "tidak",
    "kangen",
    "khayalannya",
    "khilaf",
    "khas",
    "ini",
    "kira-kira",
    "kyai",
    "kejadian",
    "kejauhan",
    "kejauhan",
    "kalah",
    "klaksonnya",
    "kalangan",
    "kelapa",
    "kelebihan",
    "klakson",
    "kalah",
    "kelihatan",
    "kalian",
    "kelihatan",
    "kelihatannya",
    "kelihatan",
    "klien-klien",
    "keliling",
    "kelima",
    "kelompok",
    "kalau",
    "kalau",
    "keluarga",
    "kelas",
    "kalau",
    "keluar",
    "keluaran",
    "keluarga",
    "keluarga",
    "keluarkan",
    "keluarkan",
    "kelulusan",
    "kalau",
    "kelihatan",
    "kelas",
    "kamu",
    "bagaimana",
    "kemalaman",
    "kemana",
    "kemana",
    "kamar",
    "kemarin",
    "kemari",
    "kemarin",
    "kembali",
    "kembarannya",
    "kembali",
    "kembali",
    "kambuh",
    "kami",
    "kamis",
    "kemana",
    "kemana",
    "kemana-mana",
    "ke monas",
    "kumpul",
    "kumpulkan",
    "kampanye",
    "kumpul",
    "kampung",
    "kampus",
    "kamar",
    "kemarin",
    "kemari",
    "kemarin",
    "kamar mandi",
    "kemarin",
    "kamis",
    "kamu",
    "kamunya",
    "kan",
    "kena",
    "kenal",
    "kanan",
    "kenapa",
    "kenapa",
    "kunci",
    "kendala",
    "kendaraan",
    "kendaraan",
    "kondisi",
    "kendala",
    "konfirmasi",
    "kangen",
    "untuk",
    "kangen",
    "untuk",
    "kini",
    "kunjungi",
    "kenal",
    "kenapa",
    "kenapa-kenapa",
    "kenapa",
    "kenapa",
    "kantor",
    "kantor",
    "kenyataan",
    "kenyataan",
    "kenyataannya",
    "kenyataannya",
    "komunikasi dan informatika",
    "komisi nasional",
    "komplek",
    "konsumennya",
    "kontrakannya",
    "koordinasikan",
    "koordinasi",
    "koordinasikan",
    "koordinat",
    "kosannya",
    "kosongkan",
    "kos",
    "kota bogor",
    "kamu",
    "seperti",
    "kepada",
    "kepala",
    "kepalaku",
    "kapan",
    "ke pantai",
    "kepada",
    "ingin",
    "kepercayaan",
    "kepercayaan",
    "terpleset",
    "kapan",
    "kapan-kapan",
    "terpotong",
    "keperluan",
    "keputusan",
    "kok",
    "kira-kira",
    "kerajinan",
    "keranjang",
    "kreativitas",
    "kreatif",
    "keren",
    "kereta",
    "kurang",
    "kerja",
    "kerja",
    "kerja",
    "kirim",
    "kerumah",
    "karena",
    "karena",
    "sama",
    "kartu",
    "kritik",
    "kartu",
    "kartunya",
    "kerudung",
    "kesampaian",
    "kesana",
    "tersedot",
    "kesal",
    "tersetrum",
    "kasih",
    "kasihan",
    "kesiangan",
    "kesiangan",
    "kasihannya",
    "kasihannya",
    "kasihannya",
    "kasihannya",
    "kasih",
    "kasihan",
    "kesini",
    "kesitu",
    "ke sekolah",
    "kesana",
    "kesana",
    "kesini",
    "kesana",
    "kesana",
    "kesitu",
    "kesukaan",
    "kesukaan",
    "kita",
    "kata",
    "katanya",
    "katanya",
    "ketawa-tawa",
    "ketemu",
    "ketika",
    "daripada",
    "ketinggalan",
    "ketinggalan",
    "ketinggian",
    "ketinggian",
    "ketika",
    "ketika",
    "ketemu",
    "ketempat",
    "ketemu",
    "ketemuan",
    "ketinggalan",
    "katanya",
    "katanya",
    "kotor",
    "tertusuk",
    "kangen",
    "kubawakan",
    "bagaimana",
    "komplit",
    "kumpul-kumpul",
    "kumpulkan",
    "kenapa",
    "kunjungannya",
    "kunjungi",
    "kuupayakan",
    "kurang pergaulan",
    "kura-kura",
    "kurangi",
    "kau",
    "seperti",
    "seperti",
    "seperti",
    "sepertinya",
    "sepertinya",
    "kenyamanan",
    "sepertinya",
    "seperti",
    "sepertinya",
    "sepertinya",
    "sepertinya",
    "sepertinya",
    "sepertinya",
    "sepertinya",
    "laba-laba",
    "lain",
    "lainnya",
    "lainnya",
    "lainnya",
    "lainnya",
    "laki-laki",
    "lama",
    "lancar-lancar",
    "lanjut",
    "lanjut usia",
    "lapangannya",
    "lapar",
    "laporannya",
    "laporkan",
    "latihan",
    "latihan",
    "latihannya",
    "latihannya",
    "latihannya",
    "kau",
    "lautnya",
    "lawannya",
    "lawannya",
    "lubang",
    "lebih",
    "lebih",
    "libur",
    "liburan",
    "liburan",
    "libur",
    "liburan",
    "hubungan jarak jauh",
    "lengkapi",
    "lepaskan",
    "letnan kolonel",
    "lagi",
    "lagi",
    "langsung",
    "langsung",
    "langsung",
    "lagu",
    "lagi",
    "lihat",
    "lihat",
    "lihat",
    "lihat-lihat",
    "kelihatannya",
    "lihatin",
    "lihatnya",
    "lihatnya",
    "lihatnya",
    "liburkan",
    "gaya hidup",
    "tautan",
    "lipat",
    "lembaga ilmu pengetahuan indonesia",
    "lipstik",
    "daftar",
    "tinggal",
    "laju",
    "lakukan",
    "lama",
    "lama-lama",
    "lemak",
    "lembar",
    "lambat",
    "lampu",
    "lumayan",
    "lumayan",
    "lancar",
    "langganan",
    "langganan",
    "lengkap",
    "lengkap",
    "langsung",
    "langsung",
    "langsung",
    "lanjut",
    "lanjut",
    "lanjutnya",
    "lantai",
    "kamu",
    "lokal",
    "lokasi",
    "kamu",
    "lokasinya",
    "tertawa",
    "belum",
    "loncat-loncat",
    "jarak jauh",
    "liburan panjang akhir pekan",
    "liburan panjang akhir pekan",
    "liburan panjang akhir pekan",
    "pecundang",
    "baterai lemah",
    "lupa",
    "lupa",
    "lapangan",
    "lepas",
    "lantai",
    "kamu",
    "kamu",
    "kamu kan",
    "luka-luka",
    "lupakan",
    "lupa",
    "kamu",
    "lewat",
    "lawan",
    "lewat",
    "lihat",
    "monas",
    "mandiri",
    "sama",
    "mamah",
    "mamahmu",
    "maaf",
    "lima belas ribu",
    "terimakasih",
    "macam-macam",
    "macam-macam",
    "macetnya",
    "main",
    "mainan",
    "mainannya",
    "mainannya",
    "mainannya",
    "mainannya",
    "mainkan",
    "mainnya",
    "maaf",
    "maafkan",
    "maafkan",
    "mahal-mahal",
    "main-main",
    "mainnya",
    "mainnya",
    "terimakasih",
    "memakai",
    "makanya",
    "terimakasih",
    "terimakasih",
    "terimakasih",
    "memakai",
    "makin-makin",
    "terimakasih",
    "maksudnya",
    "maksudnya",
    "maksudnya",
    "maksud",
    "maksudnya",
    "mall",
    "malam-malam",
    "lagi",
    "malam",
    "malas",
    "malam minggu",
    "malu-maluin",
    "mamahnya",
    "mananya",
    "mana",
    "mana-mana",
    "lagi",
    "manfaatkan",
    "manfaat",
    "manfaatkan",
    "manfaatkan",
    "mengaku",
    "makannya",
    "manggil-manggil",
    "manggil",
    "manggil",
    "manggil-manggil",
    "manggis",
    "makanya",
    "makanya",
    "makanya",
    "memangku",
    "manggil",
    "memangnya",
    "manggung",
    "manggungnya",
    "lagi",
    "manis-manis",
    "manjakan",
    "mantap",
    "mantap",
    "mantap",
    "mantap",
    "mantap",
    "mantap",
    "mantap",
    "mantap",
    "mantap",
    "teman-teman",
    "mantap",
    "mantap",
    "mantap",
    "manusia-manusia",
    "ngikut",
    "ngikut",
    "mau",
    "maunya",
    "maaf",
    "maaf-maaf",
    "maafkan",
    "marah-marah",
    "kepada",
    "kemarin",
    "menikah",
    "massal",
    "masalahnya",
    "masalah",
    "sama-sama",
    "memasang",
    "masih",
    "masih",
    "masing-masing",
    "masjid",
    "memastikan",
    "memastikan",
    "memastikan",
    "masyaallah",
    "masyaallah",
    "masyaallah",
    "matang",
    "matikan",
    "matikan",
    "matikan",
    "maunya",
    "maksimal",
    "maksimal",
    "mungkin",
    "mbak",
    "mbak",
    "mbaknya",
    "mbakku",
    "balik",
    "kembalikan",
    "balik",
    "mbaknya",
    "mbak",
    "sama",
    "dahulu",
    "mbak",
    "tidak",
    "memberikan",
    "membuat",
    "membawa",
    "macam",
    "macetnya",
    "macam",
    "macam-macam",
    "mending",
    "mudah",
    "mudah-mudahan",
    "mudah-mudahan",
    "mendingan",
    "mekkah",
    "melakukannya",
    "melanggar",
    "ikut",
    "memasukkan",
    "membalikkan",
    "membiarkannya",
    "membutuhkan",
    "mengumpulkan",
    "memikirkannya",
    "memperingati",
    "mempermasalahkan",
    "mempertanggungjawabkannya",
    "memproduksi",
    "mempromosikan",
    "menaklukkan",
    "menakutkan",
    "menanggapi",
    "menanggungnya",
    "mengunduh",
    "mengunduh",
    "mendapat",
    "mendapatkan",
    "diam",
    "mengabulkannya",
    "menggagalkan",
    "mengalahkan",
    "menggambar",
    "menggambarkan",
    "menggandeng",
    "menganggap",
    "mengganggu",
    "mengangguk",
    "mengganti",
    "menggantung",
    "mengasyikkan",
    "mengasyikkan",
    "mengatakan",
    "menggelar",
    "menggeliat",
    "menggelinding",
    "menggelitik",
    "menggembirakan",
    "membuat kepingin",
    "mengeringkannya",
    "menggunakan",
    "menggunakan",
    "menggunakan",
    "mengirimkan",
    "mengaktifkan",
    "menggoda",
    "menggugah",
    "menggunakan",
    "menggunakan",
    "mengguncang",
    "menggunakan",
    "menggunakan",
    "mengheningkan",
    "menteri perhubungan",
    "meninggal",
    "meninggalkan",
    "meninggalnya",
    "menunggang",
    "menunggu",
    "menunggumu",
    "menunjukkan",
    "menyenggol",
    "merayakannya",
    "menikah",
    "mesinnya",
    "masjid",
    "selamat",
    "mewah-mewah",
    "mau nangis",
    "mau nangis",
    "mengalami",
    "menggelar",
    "minggu",
    "menghantarkan",
    "mungkin",
    "mungkin",
    "berangkat",
    "mogok",
    "mohon",
    "mohon",
    "mahasiswamu",
    "demi apa",
    "demi apa",
    "demi apa",
    "demi apa",
    "berfikir",
    "berfikir-fikir",
    "suka berfikir",
    "memikirkan",
    "memikirkan",
    "memikirkan",
    "berfikirnya",
    "berfikirnya",
    "miliknya",
    "milikku",
    "minggir",
    "minggu",
    "minggu-minggu",
    "mingguan",
    "minggunya",
    "minggunya",
    "minta",
    "mintakan",
    "misalnya",
    "menjadi",
    "maka",
    "makan",
    "makanya",
    "terimakasih",
    "makmur",
    "makan",
    "makanan",
    "makanya",
    "terimakasih",
    "maksud",
    "maksudnya",
    "terimakasih",
    "terimakasih",
    "terimakasih",
    "maksimal",
    "maksud",
    "maksud",
    "maksudnya",
    "maksudnya",
    "malah",
    "mulai",
    "jalan",
    "jalan-jalan",
    "melakukan",
    "jalannya",
    "malam",
    "malas",
    "masuk",
    "meledak",
    "meledak",
    "malam",
    "melepas",
    "malas",
    "melanggar",
    "melanggar",
    "malah",
    "melihat",
    "melintas",
    "melakukan",
    "malam",
    "malam-malam",
    "malamnya",
    "malas",
    "melulu",
    "membahana",
    "membawaku",
    "membedakan",
    "membeli",
    "membahayakan",
    "memberikan",
    "membuat",
    "membutuhkan",
    "memang",
    "memiliki",
    "memperkuat",
    "memperpanjang",
    "mimpi",
    "mampir",
    "memperlihatkan",
    "mempersiapkan",
    "mampu",
    "mampus",
    "mana",
    "mana",
    "menang",
    "menangkan",
    "menara",
    "menarik",
    "mencapai",
    "mencari",
    "mencari",
    "mendadak",
    "mendapatkan",
    "mandat",
    "mending",
    "mendingan",
    "mondok",
    "mendongkrak",
    "mendapatkan",
    "mendukung",
    "mendukungnya",
    "mendung",
    "mana",
    "manfaat",
    "mengalami",
    "mengalir",
    "mengeluarkan",
    "mengenang",
    "mengendarai",
    "mengerti",
    "manggil",
    "minggu",
    "mingguan",
    "menggunakan",
    "menggunakan",
    "menghadap",
    "menghamili",
    "mengharap",
    "mengheningkan",
    "manggis",
    "kesal",
    "mungkin",
    "mungkin",
    "makanya",
    "makanya",
    "mengenai",
    "maksudnya",
    "minggu",
    "mingguan",
    "menggunakan",
    "menggunakan",
    "menikah",
    "menikmati",
    "manis",
    "menitikberatkan",
    "menjadi",
    "menjadi",
    "menjadi",
    "meminjam",
    "menjunjung",
    "menjawab",
    "menanti",
    "menurut",
    "minta",
    "minta",
    "mintakan",
    "mantannya",
    "mantannya",
    "mantap",
    "menanti",
    "manual",
    "menunggu",
    "menunggu",
    "menuju",
    "minum",
    "menunggu",
    "menunggu",
    "menunjukkan",
    "menunjukkan",
    "menurut",
    "menurutmu",
    "manusia",
    "menyamar",
    "menyusul",
    "mau",
    "hasil modifikasi",
    "modifikasi",
    "dimodifikasi",
    "modifikasikan",
    "modifikasikan",
    "tidak mau",
    "momennya",
    "momen",
    "momen",
    "momennya",
    "monasnya",
    "senin",
    "senin",
    "uang",
    "monyet",
    "bulan",
    "monyetnya",
    "pagi",
    "pagi",
    "datang",
    "datang-datang",
    "memerosotkan",
    "ibu",
    "mengambil foto",
    "cara mengambil fotonya",
    "motor-motor",
    "motor",
    "sampai",
    "sampai",
    "pempek",
    "memperkuat",
    "memperpanjang",
    "sudah",
    "punya",
    "marah",
    "marah-marah",
    "merantau",
    "merasa",
    "merasakannya",
    "mereka",
    "mereka",
    "marah",
    "marahan",
    "mari",
    "muridnya",
    "kesini",
    "merinding",
    "mirip",
    "mereka",
    "mereka",
    "kesana",
    "merupakan",
    "merpati",
    "merupakan",
    "masak",
    "masalah",
    "masing",
    "masing-masing",
    "masih",
    "masih",
    "masing-masing",
    "masjid",
    "meski",
    "meskipun",
    "masalah",
    "masalahnya",
    "masalah",
    "masalahnya",
    "masing",
    "masak",
    "musuhan",
    "masak",
    "mesti",
    "mesti",
    "masuk",
    "masukkan",
    "masuknya",
    "motor",
    "motor-motor",
    "motornya",
    "motornya",
    "motor",
    "mudah-mudahan",
    "semoga",
    "moga-moga",
    "mukanya",
    "mulai",
    "berlebihan",
    "mumpung",
    "naik",
    "musik",
    "musim-musim",
    "museum",
    "mestinya",
    "berputar",
    "berputar-putar",
    "mau",
    "mewah",
    "namaku",
    "mas",
    "menabrak",
    "naik",
    "nice",
    "nah itu",
    "nama-nama",
    "namanya",
    "namanya",
    "bertambah",
    "nambah-nambah",
    "nama",
    "dinamai",
    "nama",
    "menangani",
    "nangis",
    "bertanya",
    "menanyakan",
    "apa",
    "kenapa",
    "kenapa",
    "kenapa",
    "narsis",
    "menari",
    "naruh",
    "nasi goreng",
    "nasi gorengnya",
    "navigasi",
    "mendadak",
    "tidak",
    "tidak apa-apa",
    "buruan",
    "sejak",
    "bersembunyi",
    "melihat",
    "mendengkur",
    "mana",
    "tidak",
    "jongkok",
    "punya",
    "menebalkan",
    "butuh",
    "dibutuhkan",
    "kebutuhan",
    "negatif",
    "negara",
    "negeri",
    "nih",
    "menelpon",
    "menelpon",
    "bertelur",
    "menelpon",
    "menelpon",
    "menelpon",
    "menelpon",
    "menemani",
    "menembak",
    "menembaknya",
    "menembaknya",
    "menembus",
    "banget",
    "menemani",
    "menemukan",
    "menemui",
    "menemuinya",
    "menemuinya",
    "menemukannya",
    "menenangkan",
    "menendang",
    "nenek-nenek",
    "mengheningkan",
    "disini",
    "disana",
    "menengok",
    "menengoki",
    "membawa",
    "membawa",
    "menepati",
    "meneruskan",
    "pengguna internet",
    "jaringan",
    "tidak pernah",
    "tidak usah dipikirkan",
    "berita",
    "mengabadikan",
    "mengabadikan",
    "mengabari",
    "menghabiskan",
    "berbohong",
    "berpetualang",
    "berkaca",
    "kabur",
    "mengadakan",
    "berteduh",
    "meneduhkan",
    "menghadap",
    "menghadiri",
    "mengadu",
    "mengagetkan",
    "ngajak-ngajak",
    "mengajak saya",
    "mengajaknya",
    "mengajari",
    "mengajari",
    "tidak",
    "tertawa",
    "mengakui",
    "mengalah",
    "mengalahkan",
    "mengalihkan",
    "mengalir",
    "mengambang",
    "mengambil",
    "mengambilkan",
    "mengambilnya",
    "pergi ke kampus",
    "mengamuk-ngamuk",
    "menemani",
    "menghancurkan",
    "menggandeng",
    "menganggap",
    "membuat kangen",
    "menggunakan",
    "menggunakan",
    "mengangguk",
    "menganggur",
    "mengganjal",
    "mengantar",
    "mengantarkan",
    "sampai",
    "mengantongi",
    "mengantongi",
    "pergi ke kantor",
    "mengantri",
    "mengantri",
    "mengantrinya",
    "mengantuk",
    "ngapa-ngapain",
    "menghafal",
    "menghafalkan",
    "ngapain",
    "ngapain",
    "berbohong",
    "negara",
    "mengarah",
    "mengarang",
    "negaranya",
    "mengerjakan",
    "berharap",
    "harapannya",
    "mengharapkan",
    "telat",
    "mengerti",
    "berpengaruh",
    "memberi",
    "memberi",
    "memberi",
    "memberi",
    "memberinya",
    "istirahat",
    "mengasuh",
    "mengatakan",
    "mengatasi",
    "mengatasi",
    "mengatur",
    "mengawasi",
    "membuat",
    "ngasal",
    "ngasal-asalan",
    "mengkhayal",
    "mengkhayalnya",
    "membuat",
    "mengebom",
    "mengobrol",
    "membuka",
    "berkencan",
    "mengembalikan",
    "mengembalikannya",
    "mengembalikannya",
    "main band",
    "membanggakan",
    "membanggakan",
    "membangun",
    "membantai",
    "membanyol",
    "membawa",
    "membayangkan",
    "membayangkannya",
    "membayangkannya",
    "menelpon",
    "membelikan",
    "memberitau",
    "memblokir",
    "tidur",
    "berpetualang",
    "membolehkan",
    "mengebom",
    "mengebor",
    "membosankan",
    "membunuh",
    "mengebut",
    "kebut-kebutan",
    "mengebut",
    "mengebut",
    "mengecapi",
    "mengejek",
    "mengecek",
    "mengecas",
    "mengecat",
    "membuat klub",
    "mendadak",
    "mengedarkan",
    "berkencan",
    "membangun",
    "membangun",
    "mendengkur",
    "mengedit",
    "mengedit-edit",
    "mendoakan",
    "menembak",
    "membayar uang muka",
    "pergi ke dufan",
    "mendukung",
    "ngefollow",
    "mencetak gol",
    "menghalau",
    "menghargai",
    "menghibur",
    "menghina",
    "menghormati",
    "menjagakan",
    "mengajak",
    "menjalani",
    "menjamin",
    "menjanjikan",
    "mengejar",
    "mengejarnya",
    "mengejek",
    "menjiplak",
    "menjual",
    "berjubel",
    "tertawa",
    "eksis-eksisan",
    "meladeni",
    "meladeninya",
    "melahirkan",
    "mengelak",
    "menglakson",
    "melamar",
    "melamun",
    "melancong",
    "melantik",
    "melantur",
    "mengelap",
    "berjualan",
    "melatihnya",
    "melucu",
    "mengejek",
    "menenggelamkan",
    "melepas",
    "membuat alasan",
    "membuat alasannya",
    "melewati",
    "melihat",
    "melihat",
    "memperlihatkan",
    "melihatnya",
    "mengelilingi",
    "meliput",
    "melirik",
    "menggelitik",
    "disiarkan langsung",
    "pusing",
    "meluapkan",
    "mengeluarkan",
    "mengeluarkannya",
    "melucu",
    "mengeluh",
    "melukis",
    "melupakan",
    "mengelus",
    "mengembalikan",
    "mengembang",
    "mengembun",
    "ngomong",
    "ngomong-ngomong",
    "mengemis-ngemis",
    "membuat modus",
    "mengemut",
    "mengena",
    "mengenalkan",
    "mengendap",
    "begini",
    "begini",
    "mengenaskan",
    "internetan",
    "ngapain",
    "mengepel",
    "mengepelkan",
    "merakit",
    "meramal",
    "meramaikan",
    "merampok",
    "merasa",
    "merasakan",
    "merayakan",
    "merayakannya",
    "merayakannya",
    "merayu",
    "meremehkan",
    "merencanakan",
    "merepotkan",
    "berpikiran kotor",
    "meributkan",
    "merintis",
    "melakukan riset",
    "ngerinya",
    "mengerjakan",
    "merokok",
    "yang dimengerti",
    "ngertikan",
    "mengubah",
    "merugikan",
    "merugikan",
    "merusak",
    "merusakkan",
    "nongkrong",
    "ngetweet",
    "ngetweet",
    "ngetweet",
    "ngetweet",
    "ngetweetnya",
    "follow",
    "follow",
    "tidak",
    "tidak",
    "tidak",
    "tidak",
    "tidak apa-apa",
    "tidak seperti",
    "menggandeng",
    "mengganjal",
    "ganteng",
    "mengerjakan",
    "memberi",
    "membawa",
    "membuat",
    "iya",
    "tidak",
    "untuk",
    "tempat",
    "tempatku",
    "bersepeda",
    "membawa",
    "membawa",
    "nunggu",
    "menggundulinya",
    "tertawa",
    "gaya",
    "menghirup",
    "berkhayal",
    "ngikut",
    "mengedarkan",
    "mengigau",
    "iya",
    "mengizinkan",
    "mengikuti",
    "menghilang",
    "menghilangkan",
    "mimpi",
    "mimpi",
    "mimpiku",
    "mengincar",
    "menghindari",
    "menginap",
    "menginapnya",
    "mengingatkan",
    "menginjak",
    "mengikuti",
    "mengintip",
    "mengira",
    "mengiranya",
    "mengirim",
    "mengiris",
    "menghirup",
    "nangis",
    "mengisi",
    "mengitari",
    "menghitung",
    "menghitung",
    "mengajak",
    "mengajak-ajak",
    "mengajak",
    "mengajak",
    "mengajar",
    "mengajari",
    "mengajak",
    "mengajak",
    "tidak",
    "nanti",
    "nanti",
    "kos",
    "nongkrong",
    "mengaku",
    "ngikut",
    "menjalankan",
    "melamar",
    "melelang",
    "melewati",
    "melihat",
    "melihat",
    "mengumpulkan",
    "ngomong",
    "ngomongin",
    "ngomong",
    "ngomongin",
    "ngomongnya",
    "ngomong",
    "ngomongin",
    "mengumpulkan",
    "kumpul",
    "mengumpulkan",
    "mengamuk",
    "menganggur",
    "mengangkat",
    "mengantuk",
    "untuk",
    "ngobrol",
    "mengoceh",
    "mengocok",
    "mengocol",
    "mencari",
    "mengoleksi",
    "mengomel",
    "ngomongin",
    "ngomongin",
    "ngomong-ngomong",
    "ngomongnya",
    "ngomongin",
    "tempatku",
    "begitu",
    "bersepeda",
    "mengontrak",
    "ngopikan",
    "ngapain",
    "nanti",
    "bersepeda",
    "membawa",
    "membawa",
    "ngapain",
    "ngapain",
    "ngapain",
    "ngapain",
    "mengira",
    "merakit",
    "merasakan",
    "merasakan",
    "merayakan",
    "merebut",
    "merokok",
    "merasakan",
    "mengerti",
    "merusak",
    "ngasih",
    "ngasih",
    "mengubah",
    "mengitari",
    "mengucapkan",
    "ngidam",
    "mengulang",
    "kuliah",
    "mengumbar",
    "bersembunyi",
    "begitu",
    "ngopi",
    "ngopi-ngopi",
    "mengurangi",
    "menguras",
    "mengurusi",
    "mengurusinya",
    "mengurusinya",
    "usul",
    "mengusulkan",
    "hutang",
    "menghutangi",
    "tertawa",
    "kencing",
    "ini",
    "malam",
    "menipu",
    "nissan",
    "iya",
    "mengambil",
    "menelpon",
    "menelpon",
    "nama",
    "namanya",
    "namanya",
    "namanya",
    "namanya",
    "nomor",
    "tampak",
    "tampak",
    "nomor",
    "nomornya",
    "namun",
    "menunggu",
    "tungguin",
    "nenagis",
    "nanti",
    "nonton",
    "nontonnya",
    "nomor",
    "menolak",
    "menolong",
    "menolong",
    "nomor",
    "nomornya",
    "nontonnya",
    "nomor hp",
    "tidak ada",
    "pemberitahuan",
    "pemberitahuannya",
    "november",
    "sekarang",
    "kenapa",
    "nanti",
    "nanti",
    "nantinya",
    "nitip",
    "nonton",
    "nonton",
    "nanti",
    "nomor",
    "naik",
    "nunggu",
    "sampai",
    "menabung",
    "menyelesaikan",
    "menyembuhkan",
    "menyempatkan",
    "menyenangkan",
    "menyenggol",
    "bersepeda",
    "bikin sesak",
    "menyesal",
    "menyanyi",
    "ibu",
    "mencuri",
    "mencopet",
    "menyopir",
    "menyopir",
    "menyopir",
    "mencuri",
    "kok",
    "oh iya",
    "oleh-oleh",
    "oleh-oleh",
    "oleh-oleh",
    "ya tuhan",
    "ya tuhan",
    "omong doang",
    "ya tuhan",
    "ada",
    "apa",
    "operator",
    "operator",
    "pilihan",
    "pilihan",
    "tidak",
    "orang",
    "orang-orang",
    "orang alay",
    "orang gila",
    "orangnya",
    "orangtua",
    "original",
    "orang",
    "orang-orang",
    "orangnya",
    "lainnya",
    "lainnya",
    "otomatis",
    "lagi di jalan",
    "perbaikan",
    "apa-apa",
    "pabrikan",
    "pacar",
    "pacarku",
    "pagar",
    "pelit",
    "pakaiannya",
    "pakai",
    "pakaikan",
    "pakai",
    "panasnya",
    "memang",
    "panggil",
    "panggilan",
    "pantas",
    "orangtua",
    "orangtua",
    "pesta",
    "pacar",
    "pacaran",
    "pacarku",
    "pacar",
    "pacaran",
    "pacarmu",
    "pacaran",
    "pacarnya",
    "pacarnya",
    "pada",
    "padahal",
    "padahal",
    "padahalkan",
    "padahal",
    "damai",
    "pedas",
    "pegal",
    "pergi",
    "pekerjaan",
    "pelanggan",
    "plastik",
    "pelayanannya",
    "memohon",
    "pelakunya",
    "pemainnya",
    "pemakaiannya",
    "pembayarannya",
    "pembelaan",
    "pembelanjaan",
    "pembicaraan",
    "pembicaraan",
    "pembicaraan",
    "pemerintah kota",
    "pemakai motor",
    "pemerintah provinsi",
    "pencetannya",
    "pecinta",
    "pencitraan",
    "penderitaan",
    "pendiam",
    "penggantian",
    "ingin",
    "pengerjaan",
    "pengerjaannya",
    "penghargaan",
    "penggila",
    "penginapan",
    "penginapan",
    "pengumuman",
    "pengguna",
    "penggunaan",
    "perasaan",
    "perasaanku",
    "perasaanmu",
    "peduli",
    "perjalanan",
    "perkiraan",
    "perkara",
    "perkataan",
    "perkataan",
    "permainan",
    "permasalahannya",
    "pertanyaannya",
    "pertanyaannya",
    "pesan",
    "pesanan",
    "pesananku",
    "pagi",
    "pegang",
    "pagar",
    "ingin",
    "panggil",
    "pengguna",
    "pagi",
    "pagi-pagi",
    "panggil",
    "ingin",
    "inginnya",
    "pengguna",
    "pihak",
    "foto",
    "piknik",
    "gambarnya",
    "gambar",
    "gambar",
    "pijat",
    "pijatnya",
    "pemilihan gubernur",
    "ingin",
    "pinjam",
    "pinjaman",
    "pinjamkan",
    "berapa",
    "pintar",
    "berapa",
    "damai",
    "sekali",
    "pisang cokelat",
    "bagaimana",
    "pakai",
    "pakai",
    "pakai",
    "pakai",
    "pakainya",
    "pekerjaan",
    "pekerjaan",
    "paket",
    "pokok",
    "pokoknya",
    "pokoknya",
    "paket",
    "tempat",
    "memohon",
    "teman",
    "teman",
    "pulang",
    "pilih",
    "pilih",
    "pilihan",
    "pilihanmu",
    "pilihannya",
    "pilihannya",
    "memohon",
    "pelajar",
    "pulang",
    "pelanggan",
    "pulsa",
    "pulsa",
    "pemain",
    "pembelian",
    "pembangunan",
    "pembangunan",
    "pembayaran",
    "pemenang",
    "pameran",
    "panasnya",
    "pindah",
    "pindahkan",
    "pandai",
    "pendeta",
    "pindah",
    "pindahkan",
    "pendek",
    "pandangan",
    "pondok",
    "penempatan",
    "ingin",
    "pengaduan",
    "pengamatan",
    "pangandaran",
    "pengantin",
    "pengawas",
    "pengecekan",
    "pengecekan",
    "penggemar",
    "pengemudi",
    "ingin",
    "penggemar",
    "panggil",
    "panggilan",
    "panggilan",
    "pinggiran",
    "panggil",
    "pengguna",
    "panggil",
    "panggilan",
    "penggilan",
    "pinggiran",
    "pangkal",
    "pangkatan",
    "panggil",
    "ingin",
    "inginnya",
    "inginnya",
    "pengetahuan",
    "pengguna",
    "pengunjungnya",
    "pengusaha",
    "pernah",
    "pinjam",
    "panjang",
    "pinjam",
    "peningkatan",
    "pintar",
    "pantas",
    "penting",
    "penting",
    "penting",
    "pintu",
    "penuh",
    "penumpang",
    "penunggang",
    "punya",
    "punya",
    "pokoknya",
    "pokoknya",
    "pokoknya",
    "pokoknya",
    "pokoknya",
    "pokoknya",
    "ponakan-ponakan",
    "posisinya",
    "posisi",
    "positif",
    "positif",
    "foto",
    "foto-foto",
    "fotonya",
    "potongan",
    "potongannya",
    "potongannya",
    "potongannya",
    "perancis",
    "perasaan",
    "perasaanmu",
    "perasaan",
    "perbaikan",
    "perbandingannya",
    "prabayar",
    "percaya",
    "percaya",
    "produk",
    "persiapan",
    "hadir",
    "pertunjukan",
    "pergi",
    "pergi",
    "perginya",
    "perginya",
    "perhatian",
    "perhatikan",
    "perhitungan",
    "harga",
    "perlu",
    "permintaan",
    "permasalahkan",
    "permukaan",
    "permukaan",
    "pernah",
    "perangkat",
    "pernah",
    "produk",
    "produk",
    "berjanji",
    "pertama",
    "pertama",
    "pertunjukan",
    "perumahan",
    "perusahaan",
    "perusahaan",
    "perusahaan",
    "perusahaan",
    "frustasi",
    "perwakilan",
    "pasar minggu",
    "pasar rebo",
    "pasang",
    "pasangkan",
    "pusat",
    "pesawat",
    "pascabayar",
    "pssi",
    "pasti",
    "pasti",
    "pastikan",
    "pastikan",
    "pastikan",
    "pasukan",
    "pesawat",
    "petugas",
    "putih",
    "putih",
    "potongan",
    "potong",
    "potongan",
    "panas",
    "publik",
    "pulang",
    "pulang kampung",
    "pulang",
    "maaf",
    "punya",
    "punya",
    "popular",
    "pura-pura",
    "putri",
    "putih",
    "putri",
    "putri",
    "bagaimana",
    "bagaimana",
    "saya",
    "kalau",
    "kamu",
    "kita",
    "kita",
    "saya",
    "kualitas",
    "kuis",
    "tidak bisa",
    "ramai",
    "ramai-ramai",
    "rasanya",
    "realitanya",
    "resepsionis",
    "harga",
    "relasi",
    "hubungan",
    "santai",
    "tahan uji",
    "ingat",
    "mengingatkan",
    "ingat",
    "perbaiki",
    "ulangi",
    "penggantian",
    "pengulangan",
    "laporan",
    "laporan",
    "sumberdaya",
    "rasa hormat",
    "revolusi",
    "kebalikan",
    "tinjau",
    "hadiah",
    "ragunan",
    "rumah",
    "ramai",
    "rambut",
    "rumah",
    "rencana",
    "rencana",
    "rencana",
    "baris",
    "rasa",
    "rusak",
    "rasanya",
    "rasanya",
    "berapa",
    "berapa",
    "sedikit",
    "sabuk pengaman",
    "saya",
    "sekarang",
    "saja",
    "sekalian",
    "sama-sama",
    "sama-sama",
    "sampai",
    "sampaikan",
    "datangi",
    "samarinda",
    "sangat",
    "sangat",
    "uang sakuku",
    "sanggup",
    "santai-santai",
    "siapa",
    "siapa",
    "siapa",
    "sarannya",
    "sarannya",
    "saraf",
    "tidur",
    "seribuan",
    "bareng",
    "saat",
    "satuannya",
    "setuju",
    "saudara",
    "sebaliknya",
    "sabar",
    "sebagai berikut",
    "sebel",
    "sebelah",
    "sebelum",
    "sebelum",
    "sebelumnya",
    "sebenarnya",
    "sebenarnya",
    "seberapa",
    "sebagai",
    "sebagai",
    "sebagai",
    "sebagainya",
    "sibuk",
    "sebelah",
    "sebelah",
    "sebelum",
    "sebelumnya",
    "sebelum",
    "sebelum",
    "sebenarnya",
    "sebenarnya",
    "sebenarnya",
    "sebenarnya",
    "sebentar",
    "sebanyak",
    "sebingkah",
    "sabar",
    "berapa",
    "sebenarnya",
    "seberapa",
    "sebentar",
    "sabtu",
    "sebuah",
    "sibuk",
    "sebut",
    "sebutkan",
    "skandal",
    "secepatnya",
    "secepatnya",
    "sekolah",
    "sekolah",
    "beasiswa",
    "secepatnya",
    "secepatnya",
    "secara",
    "secara",
    "sudah",
    "sedap",
    "sedekah",
    "sedang",
    "sudah",
    "sedih",
    "sedikit",
    "sedekah",
    "sedikit",
    "sedikit",
    "sedang",
    "sedangkan",
    "sedotan",
    "saudara-saudara",
    "sebenarnya",
    "seberapa",
    "sebelum",
    "sebelum",
    "sebelumnya",
    "sebenarnya",
    "sebentar",
    "seberang",
    "seberangnya",
    "secepatnya",
    "rahasia",
    "keamanan",
    "semua",
    "sekata",
    "sekata-kata",
    "bekas",
    "sekalian",
    "sekolah",
    "selesai",
    "selling",
    "penjual",
    "santai",
    "smartfren",
    "semalam",
    "semangat",
    "sempat",
    "terkirim",
    "senin",
    "senang",
    "sepeda",
    "seperti",
    "september",
    "servis",
    "segala",
    "segar",
    "segera",
    "segini",
    "segitu",
    "segini",
    "sangat",
    "sehingga",
    "sehat",
    "siapkan",
    "sinyal",
    "sinyalnya",
    "satu",
    "silahkan",
    "silahkan",
    "simpan",
    "simpanan",
    "simpel",
    "sedikit",
    "saja",
    "saja",
    "sejati",
    "sekali",
    "sekali-kali",
    "sekalian",
    "sekaligus",
    "sekalinya",
    "sekarang",
    "sekarang",
    "sakit",
    "sekitar",
    "sekitaran",
    "sekolah",
    "sekolah",
    "sekolah",
    "sekarang",
    "sekarang",
    "silahkan",
    "selain",
    "selalu",
    "selama",
    "selamat",
    "selangkah",
    "selanjut",
    "selanjutnya",
    "selesai",
    "selingkuh",
    "salah",
    "silahkan",
    "silahkan",
    "selamat",
    "selamat",
    "santai",
    "seluruh",
    "seluruh",
    "selesai",
    "selesai",
    "selalu",
    "sama",
    "sombong",
    "sembahyang",
    "sambil",
    "sambil",
    "sombong",
    "sembuh",
    "sambung",
    "semacam",
    "semacam",
    "semoga",
    "semoga",
    "semangat",
    "semangat",
    "seminggu",
    "semalam",
    "semalam",
    "semoga",
    "sumpah",
    "sampai",
    "sampaikan",
    "simpati",
    "sampai",
    "sumpah",
    "sampai",
    "sampingan",
    "sempurna",
    "semester",
    "semua",
    "semua",
    "semua",
    "sana",
    "sendiri",
    "sendirian",
    "sendiri",
    "senin",
    "senang",
    "senang",
    "sengaja",
    "sangat",
    "sengaja",
    "sangat",
    "sungguh",
    "senilai",
    "jadi",
    "saudara",
    "bersaudara",
    "saudaramu",
    "bersaudara",
    "saudaranya",
    "salat",
    "maaf",
    "sepanjang",
    "seperti",
    "seperti",
    "sepertinya",
    "seperti",
    "seperti",
    "sepertinya",
    "sepertinya",
    "sepupu",
    "sepupu",
    "seputar",
    "supaya",
    "supaya",
    "sarapan",
    "seratus",
    "sering",
    "seribu",
    "sering",
    "serius",
    "suruh",
    "servisnya",
    "servis",
    "standar",
    "kalimat",
    "studi",
    "setengah",
    "setengah",
    "setengah",
    "setia",
    "setiap",
    "stiker",
    "masih",
    "setinggi",
    "setelah",
    "setelah",
    "setengah",
    "setengah",
    "persediaan",
    "setuju",
    "bodoh",
    "subjek",
    "subjek",
    "sulawesi selatan",
    "sumpah",
    "sumpah",
    "sungguh",
    "sungguh-sungguh",
    "sungguh-sungguh",
    "sungguhan",
    "subhanahu wata'ala",
    "saya",
    "saya",
    "sayang",
    "siapa",
    "siapa",
    "sudah",
    "terimakasih",
    "terimakasih",
    "bersedih",
    "kaya",
    "tidak",
    "tidak ada",
    "tidak akan",
    "tidak boleh",
    "tidak ada",
    "tidak dapat",
    "tidak ada",
    "tidak ada",
    "mandi",
    "tidak juga",
    "tidak akan",
    "tidak boleh",
    "taklukkan",
    "tidak mau",
    "saya minta",
    "tidak enak",
    "tidak nampak",
    "tanya",
    "tanya",
    "tidak apa-apa",
    "tidak apa-apa",
    "tidak suka",
    "tidak tau",
    "tanggalnya",
    "tetangganya",
    "bangun",
    "tangkap",
    "tangkinya",
    "tangguh",
    "tanggung",
    "terimakasih",
    "tanya",
    "nanti",
    "masih",
    "tau dah",
    "tau dah",
    "tau tidak",
    "tahun",
    "tahunan",
    "tau nih",
    "taunya",
    "tadi",
    "terdaftar",
    "tidak",
    "tadi",
    "tadinya",
    "tadinya",
    "tidak",
    "terbakar",
    "tebal",
    "terbengkalai",
    "teguran",
    "terjual",
    "tempat kejadian perkara",
    "tanya",
    "tanya",
    "telepon",
    "terimakasih",
    "telepon",
    "telepon",
    "tiga",
    "teman",
    "terimakasih",
    "terimakasih",
    "tentukan",
    "terbanyak",
    "teriak",
    "terpanggang",
    "tetap",
    "tetap",
    "tidak",
    "tega",
    "tengah",
    "tergantung",
    "tanggal",
    "tanggalan",
    "tinggi",
    "tanggal",
    "tunggu",
    "tagihan",
    "tanggungjawab",
    "tingkat",
    "tanggal",
    "tangan",
    "tugas",
    "terimakasih",
    "terimakasih",
    "mereka",
    "tahun",
    "terimakasih",
    "tidur",
    "tikar",
    "waktu",
    "tim nasional",
    "tinggal",
    "tinggalkan saja",
    "tinggalkan",
    "tinggal",
    "tinggi",
    "terjawab",
    "terjadi",
    "terkejut",
    "tukang",
    "tenaga kerja idonesia",
    "tempat kejadian perkara",
    "tidak paham",
    "tempat kejadian perkara",
    "terimakasih",
    "beli",
    "takut",
    "takutnya",
    "telah",
    "terlanjur",
    "telepon",
    "tolong",
    "telah",
    "tolong",
    "tolong",
    "telor",
    "telepon",
    "telepon",
    "teleponan",
    "teman",
    "tambah",
    "tumben",
    "tambah",
    "tambahan",
    "tambahan",
    "teman",
    "berteman",
    "temannya",
    "teman",
    "temani",
    "temannya",
    "temannya",
    "tempat",
    "tempat-tempat",
    "tempatnya",
    "tempat",
    "termasuk",
    "tamat",
    "temu",
    "temukan",
    "tenang",
    "tindak",
    "tanding",
    "tenang",
    "tengah",
    "tinggal",
    "tangerang",
    "tinggal",
    "tinggi",
    "tinggal",
    "tunggu",
    "tanggung",
    "tengah",
    "tinggi",
    "tangkap",
    "tongkrongan",
    "tinggal",
    "tangan",
    "tangerang",
    "tunggu",
    "tanpa",
    "tanpa",
    "tentu",
    "tanya",
    "tanya",
    "tanyakan",
    "tanya",
    "tanyakan",
    "ternyata",
    "untuk",
    "hari ini",
    "malam ini",
    "tetapi",
    "tapi",
    "tepat",
    "terimakasih",
    "terbaik",
    "terbang",
    "terbaru",
    "terbang",
    "terbentuk",
    "terbanyak",
    "terbuat",
    "tercela",
    "suka",
    "tarif",
    "target",
    "tergantung",
    "terguling",
    "terhambat",
    "terhormat",
    "terhormat",
    "teriak",
    "terjadi",
    "terjual",
    "terkait",
    "terkenal",
    "terakhir",
    "traktir",
    "terlalu",
    "terlanjur",
    "terlihat",
    "terlalu",
    "terlalu",
    "terima",
    "termasuk",
    "terminal",
    "terminat",
    "terimakasih",
    "termasuk",
    "transaksi",
    "transaksi",
    "ternyata",
    "ternyata",
    "terpotong",
    "terpuji",
    "terus",
    "terserah",
    "tertentu",
    "benar",
    "terus",
    "terpercaya",
    "terutama",
    "kebenaran",
    "mencoba",
    "terus",
    "tersebut",
    "tetap",
    "tetapi",
    "tanda tangan",
    "tentang",
    "tetapi",
    "tertawa",
    "itu",
    "twitter",
    "twitteran",
    "twitterku",
    "tukar",
    "bertukar",
    "belikan",
    "belikan",
    "belikan",
    "tukar",
    "beli",
    "beli saja",
    "tunggu",
    "tunggulah",
    "tunjukkan",
    "tunjukkan",
    "tidur",
    "televisi",
    "tweet",
    "tweet",
    "twitter",
    "twitteran",
    "kamu",
    "untuk",
    "sudah",
    "sudah",
    "sudah",
    "sudah",
    "sudah",
    "sudah",
    "tidak",
    "tidak",
    "hujan",
    "oke",
    "ulangan",
    "ulang tahun",
    "ulang tahun",
    "paman",
    "lucu",
    "lucukan",
    "utamakan",
    "untuk",
    "liburan",
    "video",
    "saya",
    "aduh",
    "aduh",
    "perempuan",
    "aduh",
    "aduh",
    "saja",
    "wakil gubernur",
    "tunggu",
    "walaupun",
    "ingin",
    "kenyang",
    "warung kopi",
    "warung tegal",
    "untuk",
    "situs",
    "situs",
    "perempuan",
    "weekday",
    "akhir pekan",
    "akhir pekan",
    "sudah",
    "apa",
    "kapan",
    "dimana",
    "ketika",
    "kenapa",
    "menang",
    "sudah",
    "waktu",
    "waktu",
    "waktunya",
    "waktunya",
    "wanita",
    "wanita",
    "wanita",
    "ada",
    "yang ada",
    "kata",
    "bekerja",
    "dunia",
    "warna",
    "warna",
    "bangsat",
    "edan",
    "ya allah",
    "ya allah",
    "ya allah",
    "ya sudah",
    "ya sudah",
    "ya sudah",
    "ya sudah",
    "ya sudah",
    "ya sudah",
    "ya sudah",
    "ya sudah",
    "ya sudahlah",
    "ya allah",
    "ya allah",
    "ya allah",
    "ya sudah",
    "tahun",
    "buku tahunan",
    "buku tahunan",
    "iya tidak",
    "ya",
    "yang",
    "yang",
    "ya",
    "ya",
    "kamu",
    "ya sudah",
    "ya sudahlah",
    "ya sudah",
    "yang terhormat",
    "ya sudah",
    "ya sudah",
    "ya sudah",
    "ya sudah",
    "ya sudah",
    "ya sudahlah",
    "ya sudah",
    "ini",
    "customer service",
    "ribu",
    "dengan",
    "tahu",
    "gambar",
    "oke",
    "dan",
    "kok",
    "dalam kota",
    "penuh",
    "ya",
    "di",
    "mati",
    "aku",
    "kembali",
    "kak",
    "kok",
    "detail",
    "pada",
    "buka",
    "terima kasih",
    "ada",
    "dong",
    "tidak",
    "hanya",
    "hati",
    "tes",
    "seperti",
    "seperti",
    "bagian",
    "apa",
    "ibu",
    "adalah",
    "terima kasih",
    "hati",
    "aburizal bakrie",
    "aburizal bakrie",
    "hatta rajasa",
    "hatta rajasa",
    "Korupsi",
    "berfikir",
    "Undang-undang",
    "peraturan",
    "Syarat",
    "Aturan",
    "Presiden",
    "ekonomi",
    "pemimpin",
    "Kinerja",
    "daerah",
    "Rakyat",
    "mekanisme",
    "rapat",
    "bertemu",
    "sambutan",
    "Kampung",
    "prospek",
    "Unggulan",
    "Menteri",
    "dan",
    "Supir",
    "caleg",
    "relawan",
    "coblos",
    "Pilih",
    "cocok",
    "Turun",
    "Senang",
    "amandemen",
    "berkualitas",
    "calon",
    "bertugas",
    "andalan"
];
